// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBYKz48JM1hLmW3TtYcWekiyFjg-mnJF0s',
    appId: '1:801751292286:web:984e78b664d4f83c867b2f',
    messagingSenderId: '801751292286',
    projectId: 'satron-da80a',
    authDomain: 'satron-da80a.firebaseapp.com',
    storageBucket: 'satron-da80a.firebasestorage.app',
    measurementId: 'G-SHKYJCKW7F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQVMdaIJDXgQ0WzwuSOSo1IVF4Tyb4LYY',
    appId: '1:801751292286:android:d8b48b4414253561867b2f',
    messagingSenderId: '801751292286',
    projectId: 'satron-da80a',
    storageBucket: 'satron-da80a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD5Aqb6_Gb8kaKbt7CQPn7c7VWgdij0QmE',
    appId: '1:801751292286:ios:3cb14caa501658af867b2f',
    messagingSenderId: '801751292286',
    projectId: 'satron-da80a',
    storageBucket: 'satron-da80a.firebasestorage.app',
    iosBundleId: 'apu.kingsley.satron',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD5Aqb6_Gb8kaKbt7CQPn7c7VWgdij0QmE',
    appId: '1:801751292286:ios:3cb14caa501658af867b2f',
    messagingSenderId: '801751292286',
    projectId: 'satron-da80a',
    storageBucket: 'satron-da80a.firebasestorage.app',
    iosBundleId: 'apu.kingsley.satron',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBYKz48JM1hLmW3TtYcWekiyFjg-mnJF0s',
    appId: '1:801751292286:web:6dc167ab568b3909867b2f',
    messagingSenderId: '801751292286',
    projectId: 'satron-da80a',
    authDomain: 'satron-da80a.firebaseapp.com',
    storageBucket: 'satron-da80a.firebasestorage.app',
    measurementId: 'G-CNV10NLRY3',
  );
}
